---
title: "Blogs"
editor: 
  markdown: 
    wrap: 72
---

我平时喜欢把学习和研究中的笔记整理出来，以推文的形式分享给大家。

这个习惯让我受益良多。

其一，写作有助于训练自己的深度思考能力。写作过程中，你需要以一种多数读者都能「读懂」的方式来组织文字。这就要求你必须从不同的角度思考你要解释的概念或模型，将其「压缩」到最基本的概念和原理层面，然后从一些生活中例子，或多数读者都熟悉的概念入手，逐渐引导读者进入新的概念和模型。有时候，这需要长久的思考，并与不同人进行讨论，根据他们的反馈调整你的表述方式。在此过程中，受益最大的是自己。很多时候，当你兴冲冲地准备开始写一篇推文时，却发现开头部分很不顺畅，这很可能是你还没有从深层理解你要介绍的东西，你只是掌握了一些表面的东西，或者只是熟悉某个模型的估计命令 (而不是原理)。然而，当你按照上述「压缩」逻辑，尝试用最精简的例子来解释概念和原理时，你对它们的理解会不断加深。

其二，写作有助于提高表达能力。许多人将语言流畅、用词华丽视为表达能力强的标志，但这只是表面现象。真正的表达能力在于，能够以听众能理解的语言，基于他们的知识背景，把自己想要传达的观点或概念讲清楚。在写作过程中，我们往往已经反复思考过如何最佳地表达，因此，当你在与别人讲解你写过的内容时，通常能够更加清晰和有条理地表达自己的想法。

&emsp;

## New 10

  - 连玉君, 2025, [如何借助 AI 工具来伴读一篇理论类的论文？](https://www.lianxh.cn/details/1571.html).  2025/04/28
  - 连玉君, 2025, [老连买电脑：ChatGPT，DeepSeek，豆包来帮忙](https://www.lianxh.cn/details/1561.html).  2025/04/05
  - 连玉君, 2025, [异质性分析：如何避免“事后看碟下菜”？](https://www.lianxh.cn/details/1556.html).  2025/03/30
  - 连玉君, 2025, [异质性分析：揭示理论成立的边界条件](https://www.lianxh.cn/details/1555.html).  2025/03/29
  - 连玉君, 2025, [Stata：如何永久修改我的PERSONAL文件夹的位置？](https://www.lianxh.cn/details/1538.html).  2025/01/21
  - 连玉君, 2025, [Stata：回归分析中的权重问题-aweight-fweight](https://www.lianxh.cn/details/1533.html).  2025/01/06
  - 连玉君, 2024, [Stata绘图：如何调整图形的纵横比？](https://www.lianxh.cn/details/1528.html).  2024/12/26
  - 颜国强,连玉君, 2024, [tidyplots：跟 ggplot2 说再见吧！](https://www.lianxh.cn/details/1513.html).  2024/12/06
  - 连玉君, 2024, [ttestplus：组间均值差异统计和检验](https://www.lianxh.cn/details/1508.html).  2024/12/02
  - 连玉君, 2024, [从 Stata 到 R：如何使用 tag() 和 if_else() 标记分组中的首个观测](https://www.lianxh.cn/details/1495.html).  2024/11/06



## Hot 10

  - 连玉君, 2020, [Stata: 如何检验分组回归后的组间系数差异？](https://www.lianxh.cn/details/19.html), 连享会 No.19.  Hits: 107757
  - 王若溪, 连玉君, 2020, [Stata结果输出：pwcorr_a输出相关系数矩阵](https://www.lianxh.cn/details/348.html), 连享会 No.348.  Hits: 103441
  - 游万海, 连玉君, 2020, [Stata: 面板数据模型一文读懂](https://www.lianxh.cn/details/122.html), 连享会 No.122.  Hits: 98131
  - 杨柳, 连玉君, 2020, [Stata: 工具变量法 (IV) 也不难呀！](https://www.lianxh.cn/details/31.html), 连享会 No.31.  Hits: 72251
  - 杨鑫, 秦利宾, 连玉君, 2020, [Stata：聚类调整后的标准误-Cluster-SE](https://www.lianxh.cn/details/155.html), 连享会 No.155.  Hits: 46120
  - 连玉君, 杨柳, 2020, [Stata：Logit模型一文读懂](https://www.lianxh.cn/details/170.html), 连享会 No.170.  Hits: 43315
  - 连玉君, 杨柳, 2020, [Stata: 边际效应分析](https://www.lianxh.cn/details/64.html), 连享会 No.64.  Hits: 41968
  - 周洋, 连玉君, 李森林, 2020, [平方项 = 倒U型 ？](https://www.lianxh.cn/details/70.html), 连享会 No.70.  Hits: 38528
  - 连玉君, 张静瑶, 2020, [加入控制变量后结果悲催了！](https://www.lianxh.cn/details/135.html), 连享会 No.135.  Hits: 35510
  - 陈贤孟, 2020, [正确姿势：回归系数的解释与评估](https://www.lianxh.cn/details/277.html), 连享会 No.277.  Hits: 33325


## ALL 

- 连玉君, 2025, [如何借助 AI 工具来伴读一篇理论类的论文？](https://www.lianxh.cn/details/1571.html)
- 连玉君, 2025, [老连买电脑：ChatGPT，DeepSeek，豆包来帮忙](https://www.lianxh.cn/details/1561.html)
- 连玉君, 2025, [异质性分析：如何避免“事后看碟下菜”？](https://www.lianxh.cn/details/1556.html)
- 连玉君, 2025, [异质性分析：揭示理论成立的边界条件](https://www.lianxh.cn/details/1555.html)
- 连玉君, 2025, [Stata：如何永久修改我的PERSONAL文件夹的位置？](https://www.lianxh.cn/details/1538.html)
- 连玉君, 2025, [Stata：回归分析中的权重问题-aweight-fweight](https://www.lianxh.cn/details/1533.html)
- 连玉君, 2024, [Stata绘图：如何调整图形的纵横比？](https://www.lianxh.cn/details/1528.html)
- 颜国强,连玉君, 2024, [tidyplots：跟 ggplot2 说再见吧！](https://www.lianxh.cn/details/1513.html)
- 连玉君, 2024, [ttestplus：组间均值差异统计和检验](https://www.lianxh.cn/details/1508.html)
- 连玉君, 2024, [从 Stata 到 R：如何使用 tag() 和 if_else() 标记分组中的首个观测](https://www.lianxh.cn/details/1495.html)
- 连玉君, 2024, [Stata2R：那些 R 中的 _N 和 _n 替代技巧](https://www.lianxh.cn/details/1494.html)
- 连玉君, 2024, [R数据处理-多条件判断：ifelse() 和 case_when()](https://www.lianxh.cn/details/1493.html)
- 连玉君, 2024, [VScode插件：安装、配置和使用](https://www.lianxh.cn/details/1490.html)
- 连玉君, 2024, [从基础到 AI 助手：Python 用户最爱的 VScode 插件清单](https://www.lianxh.cn/details/1489.html)
- 连玉君, 2024, [TeXStudio：无法正常显示中文字符怎么办？](https://www.lianxh.cn/details/1488.html)
- 连玉君, 2024, [RStudio常用的快捷键一览](https://www.lianxh.cn/details/1481.html)
- 连玉君, 2024, [递归算法：快速排序的 R、Stata 和 Python 实现](https://www.lianxh.cn/details/1480.html)
- 连玉君, 2024, [R语言如何实现Stata中的local功能？](https://www.lianxh.cn/details/1478.html)
- 连玉君, 2024, [Markdown：连老师的Typora主题模板css文件下载](https://www.lianxh.cn/details/1426.html)
- 连玉君, 2024, [执行PSM匹配后观察值会减少吗？](https://www.lianxh.cn/details/1418.html)
- 连玉君, 2024, [快速查看ado源文件的两种方法](https://www.lianxh.cn/details/1396.html)
- 连玉君, 2024, [借助ChatGPT4o学习排序算法：AI代码助手好酸爽！](https://www.lianxh.cn/details/1393.html)
- 连玉君, 2024, [VScode：实用 Markdown 插件推荐](https://www.lianxh.cn/details/1390.html)
- 连玉君, 2024, [getiref：快速获得文献的引文和PDF原文](https://www.lianxh.cn/details/1382.html)
- 连玉君, 2024, [Stata结果输出：手动添加带星号的统计量](https://www.lianxh.cn/details/1365.html)
- 连玉君, 2024, [antrho与Fisher转换：heckman和treareg等命令中参数含义](https://www.lianxh.cn/details/1361.html)
- 连玉君, 2024, [antrho与Fisher转换：heckman和treareg等命令中参数含义](https://www.lianxh.cn/details/1358.html)
- 杨涵慧, 连玉君, 2024, [Stata绘图：插图！子图！grinset](https://www.lianxh.cn/details/1356.html)
- 连玉君, 2024, [多组成绩调整的简便方法：固定效应模型妙用](https://www.lianxh.cn/details/1343.html)
- 连玉君, 2024, [Stata 绘图：图形中的中文和英文能否设定为不同的字体](https://www.lianxh.cn/details/1335.html)
- 连玉君, 2023, [Stata编程：快速查找Stata代码片段](https://www.lianxh.cn/details/1319.html)
- 连玉君, 2023, [ivreghdfe-高维固定效应IV估计：错误信息处理-817 lines skipped](https://www.lianxh.cn/details/1318.html)
- 连玉君, 2023, [ivreghdfe-高维固定效应IV估计：错误信息处理-817 lines skipped](https://www.lianxh.cn/details/1299.html)
- 连玉君, 2023, [字符函数ustrregexm()：文字变量匹配中的英文字母大小写问题](https://www.lianxh.cn/details/1283.html)
- 连玉君, 2023, [刺猬与狐狸：Stata与R语言常用命令等价对比](https://www.lianxh.cn/details/1270.html)
- 冯超楠, 2023, [连玉君Stata33讲：面板数据模型简介-FE和RE有何区别？](https://www.lianxh.cn/details/1110.html)
- 连玉君, 2023, [最后一周：如何修改我的毕业论文？](https://www.lianxh.cn/details/1181.html)
- 连玉君, 2023, [连玉君：我与ChatGPT聊了一个月](https://www.lianxh.cn/details/899.html)
- 连玉君, 2022, [Marp幻灯片模板：用Markdown快速写幻灯片](https://www.lianxh.cn/details/1059.html)
- 连玉君, 2022, [Stata绘图：唯美的函数图-自定义水平附加线和竖直附加线](https://www.lianxh.cn/details/1064.html)
- 连玉君, 2022, [Stata101：人手一份的入门指南](https://www.lianxh.cn/details/1065.html)
- 连玉君, 2022, [LaTeX：TeXStudio编辑器快捷键大全](https://www.lianxh.cn/details/945.html)
- 连玉君, 2022, [我为什么越跑越肥？交乘项系数的直观解释](https://www.lianxh.cn/details/862.html)
- 连玉君, 2022, [图解Lasso系列A：Lasso的变量筛选能力](https://www.lianxh.cn/details/849.html)
- 连玉君, 2021, [用VScode正则表达式转换Markdown和LaTeX链接](https://www.lianxh.cn/details/839.html)
- 连玉君, 2021, [聊聊Stata中的profile文件-第二季](https://www.lianxh.cn/details/672.html)
- 连玉君, 2021, [AxMath-设置字体-伪装成Word数学公式](https://www.lianxh.cn/details/668.html)
- 史津宇, 连玉君, 2021, [Stata：投资组合有效边界](https://www.lianxh.cn/details/595.html)
- 连玉君, 2021, [连玉君的链接](https://www.lianxh.cn/details/79.html)
- 连玉君, 2021, [毕业季：如何修改你的毕业论文？](https://www.lianxh.cn/details/28.html)
- 连玉君, 2021, [Stata：提问时请务必用 dataex 命令](https://www.lianxh.cn/details/82.html)
- 连玉君, 2021, [内生性：来源及处理方法-幻灯片下载](https://www.lianxh.cn/details/538.html)
- 连玉君, 2021, [Stata错误信息-stacktrace not available：安装路径中不要包含中文字符和空格](https://www.lianxh.cn/details/539.html)
- 连玉君, 2021, [rddensity, lpdensity无法安装？那就手动安装](https://www.lianxh.cn/details/518.html)
- 严子凯, 连玉君, 2021, [Stata-Mata系列 (二)：Mata与Stata的交互](https://www.lianxh.cn/details/515.html)
- 连玉君, 2021, [Stata安装路径中不要包含中文字符和空格：stacktrace not available错误信息](https://www.lianxh.cn/details/511.html)
- 连玉君, 2020, [Stata与LaTeX的完美结合](https://www.lianxh.cn/details/485.html)
- 徐云娇, 连玉君, 2020, [Stata：数值求解极大值及 MLE 示例](https://www.lianxh.cn/details/468.html)
- 连玉君, 2020, [字符编码问题三个不可见的字符（0xEF-0xBB-0xBF，即BOM）](https://www.lianxh.cn/details/423.html)
- 连玉君, 2020, [可汗学院风格电子板书攻略：Wacom+ArtRage](https://www.lianxh.cn/details/416.html)
- 连玉君, 2020, [Stata：在线可视化模拟-OLS-的性质](https://www.lianxh.cn/details/384.html)
- 朱磊, 连玉君, 2020, [Stata：今天你table了吗？图片版](https://www.lianxh.cn/details/386.html)
- 连玉君, 2020, [Stata：文字型日期格式的转换](https://www.lianxh.cn/details/390.html)
- 连玉君, 2020, [Stata：因变量是类别变量时采用什么方法估计？](https://www.lianxh.cn/details/382.html)
- 侯新烁, 连玉君, 2020, [快速呈现常用分布临界值表](https://www.lianxh.cn/details/362.html)
- 连玉君, 2020, [公司财务-投资组合Stata实现-Berk-Corporate-Finance-Chapter-11-Examples](https://www.lianxh.cn/details/413.html)
- 连玉君, 许梦洁, 2020, [Stata：系数为何不显著？GIF演示OLS的性质.md](https://www.lianxh.cn/details/402.html)
- 连玉君, 2020, [Stata：dofile转PDF制作讲义方法](https://www.lianxh.cn/details/367.html)
- 连玉君, 2020, [Stata：普通年金现值系数表](https://www.lianxh.cn/details/392.html)
- 连玉君, 2020, [Stata：根据当前日期返回是周几](https://www.lianxh.cn/details/397.html)
- 连玉君, 2020, [Stata：聚类调整标准误笔记](https://www.lianxh.cn/details/404.html)
- 连玉君, 2020, [Stata：配对对象的均值-(俄罗斯方块移动)](https://www.lianxh.cn/details/407.html)
- 王若溪, 连玉君, 2020, [Stata结果输出：pwcorr_a输出相关系数矩阵](https://www.lianxh.cn/details/348.html)
- 连玉君, 2020, [Stata绘图：怎么在Stata图形中附加水平线或竖直线？](https://www.lianxh.cn/details/356.html)
- 连玉君, 2020, [Stata程序：是否有类似-Python-中的-zip()-函数](https://www.lianxh.cn/details/347.html)
- 连玉君, 2020, [Stata程序：我的程序多久能跑完？](https://www.lianxh.cn/details/346.html)
- 连玉君, 2020, [Stata程序：切割文件路径和文件名](https://www.lianxh.cn/details/344.html)
- 连玉君, 2020, [Stata绘图：重新定义坐标轴刻度标签](https://www.lianxh.cn/details/360.html)
- 卢家锐, 连玉君, 2020, [Stata绘图：用-bytwoway-实现快速分组绘图](https://www.lianxh.cn/details/357.html)
- 连玉君, 2020, [Stata绘图：制作教学演示动态图-GIF](https://www.lianxh.cn/details/351.html)
- 连玉君, 2020, [Stata基础：数据显示格式和四舍五入](https://www.lianxh.cn/details/309.html)
- 连玉君, 2020, [Stata数据处理：ftree命令-用txt文档记录文件夹结构](https://www.lianxh.cn/details/314.html)
- 连玉君, 2020, [Stata数据处理：分年度-行业计算销售额前四名的行业占比](https://www.lianxh.cn/details/317.html)
- 连玉君, 2020, [Markdown：五分钟Markdown教程](https://www.lianxh.cn/details/300.html)
- 连玉君, 2020, [Stata新命令：ereplace-egenmore-egenmisc](https://www.lianxh.cn/details/335.html)
- 连玉君, 2020, [Stata数据处理：物价指数-(CPI)-的导入和转换](https://www.lianxh.cn/details/323.html)
- 谢作翰, 连玉君, 2020, [Stata小白系列之二：数据拆分与合并](https://www.lianxh.cn/details/312.html)
- 连玉君, 2020, [Stata数据处理：如何提取某个变量有记录的第一年的年份](https://www.lianxh.cn/details/318.html)
- 连玉君, 2020, [Stata小抄：一组图记住Stata常用命令](https://www.lianxh.cn/details/310.html)
- 连玉君, 2020, [Markdown图床：我们的图片存在哪里？](https://www.lianxh.cn/details/296.html)
- 谢作翰, 连玉君, 2020, [Stata小白系列之一：调入数据](https://www.lianxh.cn/details/311.html)
- 连玉君, 2020, [Markdown教程之LaTeX数学公式简介](https://www.lianxh.cn/details/298.html)
- 连玉君, 2020, [神器-数学公式识别工具-mathpix](https://www.lianxh.cn/details/284.html)
- 连玉君, 2020, [Stata基础：一些漂亮的字符画](https://www.lianxh.cn/details/288.html)
- 陈贤孟, 2020, [正确姿势：回归系数的解释与评估](https://www.lianxh.cn/details/277.html)
- 连玉君, 2020, [连玉君Markdown笔记](https://www.lianxh.cn/details/286.html)
- 连玉君, 杨柳, 2020, [Stata：Logit模型一文读懂](https://www.lianxh.cn/details/170.html)
- 连玉君, 2020, [Markdown中书写LaTeX数学公式简介](https://www.lianxh.cn/details/250.html)
- 连玉君, 2020, [Stata：图示连续变量的连续边际效应](https://www.lianxh.cn/details/189.html)
- 连玉君, 2020, [Stata：图示苹果公司(APPL)历年现金股利](https://www.lianxh.cn/details/209.html)
- 连玉君, 2020, [Stata：xtabond命令中的endog()选项设定问题](https://www.lianxh.cn/details/218.html)
- 连玉君, 2020, [Stata: 如何快速合并 3500 个无规则命名的数据文件？](https://www.lianxh.cn/details/227.html)
- 连玉君, 2020, [Stata: 实时估计个股贝塔(beta)系数](https://www.lianxh.cn/details/215.html)
- 顾小龙, 连玉君, 2020, [Stata帮助和网络资源汇总(持续更新中)](https://www.lianxh.cn/details/187.html)
- 卢家锐, 连玉君, 2020, [哇！Stata参考书和经典教材！](https://www.lianxh.cn/details/188.html)
- 连玉君, 2020, [Stata15快捷键：键盘就是你的武器](https://www.lianxh.cn/details/214.html)
- 杨柳, 连玉君, 2020, [Stata: 工具变量法 (IV) 也不难呀！](https://www.lianxh.cn/details/31.html)
- 陈鑫梅, 连玉君, 2020, [Stata：刀切法-去一法-Jackknife 简介](https://www.lianxh.cn/details/275.html)
- 连玉君, 2020, [Stata绘图：用暂元统一改变图形中的字号](https://www.lianxh.cn/details/274.html)
- 杨柳, 连玉君, 2020, [Stata因子变量：虚拟变量-交乘项批量处理](https://www.lianxh.cn/details/180.html)
- 连玉君, 2020, [Stata：gen 和 egen 中的 sum() 函数异同](https://www.lianxh.cn/details/174.html)
- 杨鑫, 秦利宾, 连玉君, 2020, [Stata：聚类调整后的标准误-Cluster-SE](https://www.lianxh.cn/details/155.html)
- 连玉君, 杨柳, 2020, [Stata：因子变量全攻略](https://www.lianxh.cn/details/160.html)
- 连玉君, 2020, [在 Markdown 中使用表情符号](https://www.lianxh.cn/details/172.html)
- 连玉君, 2020, [Stata：聊聊 profile.do 文件](https://www.lianxh.cn/details/77.html)
- 连玉君, 2020, [Stata：reghdfe命令报错问题](https://www.lianxh.cn/details/157.html)
- 连玉君, 2020, [交乘项-交叉项的中心化问题](https://www.lianxh.cn/details/137.html)
- 连玉君, 2020, [毕业答辩：我准备好了！](https://www.lianxh.cn/details/125.html)
- 连玉君, 陈鑫梅, 2020, [可重复性研究：如何保证你的研究结果可重现？](https://www.lianxh.cn/details/124.html)
- 连玉君, 张静瑶, 2020, [加入控制变量后结果悲催了！](https://www.lianxh.cn/details/135.html)
- 周洋, 连玉君, 李森林, 2020, [平方项 = 倒U型 ？](https://www.lianxh.cn/details/70.html)
- 游万海, 连玉君, 2020, [Stata: 面板数据模型一文读懂](https://www.lianxh.cn/details/122.html)
- 连玉君, 杨柳, 2020, [Stata: 边际效应分析](https://www.lianxh.cn/details/64.html)
- 连玉君, 2020, [Stata黑白图形模板：中文期刊风格的纯黑白图形](https://www.lianxh.cn/details/61.html)
- 吴世飞, 连玉君, 2020, [残差是个宝：盈余管理、过度投资、超额收益怎么算？](https://www.lianxh.cn/details/103.html)
- 连玉君, 2020, [如何比较解释变量的系数相对大小？](https://www.lianxh.cn/details/86.html)
- 连玉君, 2020, [Stata: 如何检验分组回归后的组间系数差异？](https://www.lianxh.cn/details/19.html)
- 于翔, 连玉君, 2020, [Stata中文乱码转码顽疾解决方法-批量转换](https://www.lianxh.cn/details/55.html)
- 刘杨, 连玉君, 2020, [Stata可视化：让他看懂我的结果！coefplot-arrowplot](https://www.lianxh.cn/details/45.html)
- 连玉君, 2020, [gInk：一款好用的屏幕标注写画软件](https://www.lianxh.cn/details/27.html)
- 连玉君, 2020, [Endnote 使用说明和自定义中文期刊模板](https://www.lianxh.cn/details/29.html)
- 连玉君, 2020, [一个博士生应该掌握哪些工具和武器](https://www.lianxh.cn/details/30.html)
- 连玉君, 2020, [Stata 新命令：多断点 RDD 分析 - rdmc](https://www.lianxh.cn/details/26.html)
- 连玉君, 2020, [Sai2: 一款流畅的电子板书软件](https://www.lianxh.cn/details/21.html)
- 连玉君, 2020, [直播电子板书：Word, PPT, PDF 手写批注很轻松](https://www.lianxh.cn/details/16.html)
- 连玉君, 2020, [教师利器 - ZoomIt 4.5 屏幕缩放标注小软件](https://www.lianxh.cn/details/14.html)
- 连玉君, 2020, [Stata Plus-连老师的 Stata 外部命令集 (Update)](https://www.lianxh.cn/details/15.html)
- 连玉君, 2020, [协整：醉汉牵着一条狗](https://www.lianxh.cn/details/98.html)
- 连玉君, 2019, [mdnice.cn——Markdown、知乎、公众号排版神器](https://www.lianxh.cn/details/83.html)
- 连玉君, 2019, [两种网页转Markdown的简便方法](https://www.lianxh.cn/details/32.html)
- 连玉君, 2019, [Stata：回归结果中不报告行业虚拟变量的系数](https://www.lianxh.cn/details/5.html)
- 谢作翰, 连玉君, 2019, [普林斯顿Stata教程(一) - Stata数据处理](https://www.lianxh.cn/details/152.html)
- 连玉君, 2019, [Stata: gen 命令中的 group() 函数的潜在风险](https://www.lianxh.cn/details/100.html)
- 游万海, 连玉君, 2019, [Stata: 外部命令的搜索、安装与使用](https://www.lianxh.cn/details/1.html)
