---
title: "Codes"
editor: 
  markdown: 
    wrap: 72
---

Many of the links below will take you to content on GitHub
([my github](https://github.com/arlionn)).

- `lianxh`：在 Stata 中快速搜索 [lianxh.cn](https://www.lianxh.cn) 推文并按指定格式输出
  - 连享会, 2020, [ssc install lianxh：你想要的 Stata 都在这里](https://www.lianxh.cn/details/233.html)
  - 连享会, 2023, [新版lianxh命令发布了！](https://www.lianxh.cn/details/1296.html)

- `bdiff`：组间系数差异检验
  - 李烨阳, 2023, [Stata：自己动手做组间系数差异检验-bootstrap-bdiff](https://www.lianxh.cn/details/1286.html).
  - 连玉君, 2020, [Stata: 如何检验分组回归后的组间系数差异？](https://www.lianxh.cn/details/19.html).
- `winsor2`：批量缩尾处理
  - 袁煜玲, 2021, [winsor2：离群值和异常值的缩尾处理](https://www.lianxh.cn/details/562.html).
- `ihelp` / `wwwhelp`  
  - 连享会, 2024, [ihelp: 快速打开Stata帮助文件PDF手册](https://www.lianxh.cn/details/1416.html).
  - Chen Yongli, **Lian Yujun**\*. Browse and cite Stata manuals easily: the `wwwhelp` command. **Stata Journal**, 2024, 24 (1): 161–168. [-PDF-](https://file-lianxh.oss-cn-shenzhen.aliyuncs.com/Refs/LianPub/Chen-Lian-2024-SJ-wwwhelp-ihelp.pdf). 安装：`ssc install ihelp, replace`
- `getiref`
  - 连玉君, 2024, [getiref：快速获得文献的引文和PDF原文](https://www.lianxh.cn/details/1382.html).
- `sftt`：双边随机边界模型
  - **Lian Yujun**, Chang Liu, Christopher F. Parmeter. Two-tier stochastic frontier analysis using Stata. **Stata Journal**, 2023, 23(1): 197-229. [-Link-](https://journals.sagepub.com/doi/abs/10.1177/1536867X231162033), [-PDF-](https://file.lianxh.cn/Refs/LianPub/Lian-2023-SJ-sftt-Two-tier-SFA.pdf), [Codes & Data](https://gitee.com/arlionn/sftt), [github](https://github.com/arlionn/sftt). 安装：`net install st0705.pkg, all replace` 
- `hhi5`：赫芬达尔指数
  - 连享会, 2020, [Stata数据处理：赫芬达尔指数-(hhi5)-命令介绍](https://www.lianxh.cn/details/327.html)

- `xtbalance`：非平衡面板 &rarr; 平衡面板
  - 吴雄, 2020, [Stata数据处理：xtbalance-非平衡面板之转换](https://www.lianxh.cn/details/316.html).
