---
title: "Publications"
editor: visual
---


::: {.callout-note}
## Links

>- **Google Scholar**: <https://scholar.google.com/citations?user=tlkDP2AAAAAJ>
>- **ORCID**: <https://orcid.org/0000-0002-2011-7535>
>- **ResearchGate:** <https://www.researchgate.net/profile/Yujun-Lian>
:::

&emsp;

## 期刊论文

-   **连玉君**, 李鑫. 完全刑责年龄法律对未成年人犯罪行为的威慑作用研究. **统计研究**, 2025, 已接受. [工作论文版](https://file-lianxh.oss-cn-shenzhen.aliyuncs.com/Refs/LianPub/%E8%BF%9E%E7%8E%89%E5%90%9B-%E6%9D%8E%E9%91%AB-2024-%E7%BB%9F%E8%AE%A1%E7%A0%94%E7%A9%B6-RDD-%E6%9C%AA%E6%88%90%E5%B9%B4%E4%BA%BA.pdf)
-   **连玉君**, 李鑫. 失去的十年:日本应对广场协议的政策效应研究. **中山大学学报** (社会科学版), 2025 (1): 185-196. [-Link-](https://link.cnki.net/doi/10.13471/j.cnki.jsysusse.2025.01.020), [-PDF-](https://bar.cnki.net/bar/download/order?id=Pmp%2F5es3RB81cmauPwpbvsPMJcfwHgIZAnUyOJG6Kdog%2BHL%2FGFrGhKahW4YGMC%2BS9rApGw1Kn1Osj2RxbQfKvjCe6SDJA%2FE4K5lDg6WoZeh7b5mY%2FmsIpB5E%2FKF94iQVwddxEU3rL3oTHoiWc6PitFK57xT%2B8LhM%2BfEqYWvBGm0igmLMld3nSvbU4a5%2BOkNaUlSU0HSLnl9m7MwOtW%2FIk9GlczRq40icS9q1bpEM6d9lgv7q8C%2BP7FPVW3hwYPcqveGzrp%2B41EH7caBaJ8FVkg%3D%3D)
-   Yan, C., **Lian, Y.**, Xu, X., & Chen, C.-C., Share pledge lending, monetary policy, and shadow banking nexus. 2025, **Pacific-Basin Finance Journal**, Online. [Link](https://doi.org/10.1016/j.pacfin.2025.102772)
-   **Lian, Y.**, J. Wang, M. Huang. Fast or Slow: Unveiling the Speed of Market Leverage Adjustment in China. 2024, **Pacific-Basin Finance Journal**, Online. [Link](https://doi.org/10.1016/j.pacfin.2024.102423), [PDF](https://file-lianxh.oss-cn-shenzhen.aliyuncs.com/Refs/LianPub/Lian_2024_PBFJ_proof.pdf)
-   Zhou, K., Guan, Z., & **Lian, Y.** (2024). Carbon mitigation effect of emission trading product: Perspective from intra-industry carbon leakage. **Energy Economics**, 107966, Online. [Link](https://doi.org/10.1016/j.eneco.2024.107966) (rep), [PDF](https://file-lianxh.oss-cn-shenzhen.aliyuncs.com/Refs/LianPub/Lian-2024-EE_Preproof.pdf), [Google](https://scholar.google.com/scholar?q=Carbon%20mitigation%20effect%20of%20emission%20trading%20product:%20Perspective%20from%20intra-industry%20carbon%20leakage).
-   Yang, L., Cao, X. J., Wang, Y., **Lian, Y.**, & Guo, Z. (2024). Does metro expansion matter? Metro network enhances metro mode share of commuters living away from stations, but not those near stations. **Travel Behaviour and Society**, 34, 100664. [Link](https://doi.org/10.1016/j.tbs.2023.100664), [PDF](https://file-lianxh.oss-cn-shenzhen.aliyuncs.com/Refs/LianPub/Yang_Lian_2024_TBS.pdf).
-   程晓刚, 宋常, **连玉君**, 毕功兵. 创新成功与企业供应链融资\[J\]. **中国软科学**, 2024(2): 113-122.
-   Chen Yongli, **Lian Yujun**\*. Browse and cite Stata manuals easily: the `wwwhelp` command. **Stata Journal**, 2024, 24 (1): 161–168. [-PDF-](https://file-lianxh.oss-cn-shenzhen.aliyuncs.com/Refs/LianPub/Chen-Lian-2024-SJ-wwwhelp-ihelp.pdf). 安装：`ssc install ihelp, replace`
-   **Lian Yujun**, Chang Liu, Christopher F. Parmeter. Two-tier stochastic frontier analysis using Stata. **Stata Journal**, 2023, 23(1): 197-229. [-Link-](https://journals.sagepub.com/doi/abs/10.1177/1536867X231162033), [-PDF-](https://file.lianxh.cn/Refs/LianPub/Lian-2023-SJ-sftt-Two-tier-SFA.pdf), [Codes & Data](https://gitee.com/arlionn/sftt), [github](https://github.com/arlionn/sftt). 安装：`net install st0705.pkg, all replace`
-   **连玉君**, 刘畅. 精准问询：来自年报问询和控股股东股权质押的证据, **山西财经大学学报**. 2023, 45(1): 99-114. [-Link-](https://d.wanfangdata.com.cn/periodical/sxcjdxxb202301008).
-   Yang, L., Wang, Y., **Lian, Y.**, Dong, X., Liu, J., Liu, Y., & Wu, Z. (**2022**). Rational planning strategies of urban structure, metro, and car use for reducing transport carbon dioxide emissions in developing cities. **Environment, Development and Sustainability**, 25(7), 6987–7010. [-Link-](https://doi.org/10.1007/s10668-022-02344-0), [-PDF-](https://link.springer.com/content/pdf/10.1007/s10668-022-02344-0.pdf).
-   **连玉君**, 李鑫. 合成控制法中的安慰剂检验改进研究——基于准标准化转换的统计推断. **统计研究**, 2022 (8): 115-128. [Codes](https://gitee.com/arlionn/synthsd), [-PDF-](https://file-lianxh.oss-cn-shenzhen.aliyuncs.com/Refs/LianPub/%E8%BF%9E%E7%8E%89%E5%90%9B-%E6%9D%8E%E9%91%AB-2022-%E7%BB%9F%E8%AE%A1%E7%A0%94%E7%A9%B6-%E6%A0%A1%E6%A0%B7-%E9%9D%9E%E6%AD%A3%E5%BC%8F%E7%89%88.pdf)
-   李增福，陈俊杰，**连玉君**(\*)，李铭杰. 经济政策不确定性与企业短债长用, **管理世界**, 2022 (1): 77-89. [-PDF-](https://file-lianxh.oss-cn-shenzhen.aliyuncs.com/Refs/LianPub/%E6%9D%8E%E5%A2%9E%E7%A6%8F-%E8%BF%9E%E7%8E%89%E5%90%9B-2022-%E7%AE%A1%E7%90%86%E4%B8%96%E7%95%8C-%E7%BB%8F%E6%B5%8E%E6%94%BF%E7%AD%96%E4%B8%8D%E7%A1%AE%E5%AE%9A%E6%80%A7%E4%B8%8E%E4%BC%81%E4%B8%9A%E7%9F%AD%E5%80%BA%E9%95%BF%E7%94%A8.pdf)
-   李增福，黄家慧，**连玉君**(\*)，非国有资本参股与国企技术创新，**统计研究**，2021 (1): 119-131. [-Link-](https://t.cnki.net/kcms/detail?v=X6oIUGaNdGl02O8hLreyMfQ1AB_lc7oZyruBxG73K9OVEB6dr7g6N2LQ1UIioRWcfRv5Ih1EskkwhzyU6x-XF-fvlUvmr2hJwiEvVfIzYhBskUjtHXBQNfai1jy4bto0&uniplatform=NZKPT), [-PDF-](https://file-lianxh.oss-cn-shenzhen.aliyuncs.com/Refs/LianPub/%E6%9D%8E%E5%A2%9E%E7%A6%8F-%E8%BF%9E%E7%8E%89%E5%90%9B-2021-%E5%B8%A6%E5%B0%81%E9%9D%A2-%E7%BB%9F%E8%AE%A1%E7%A0%94%E7%A9%B6-%E9%9D%9E%E5%9B%BD%E6%9C%89%E8%B5%84%E6%9C%AC%E5%8F%82%E8%82%A1%E4%B8%8E%E5%9B%BD%E4%BC%81%E6%8A%80%E6%9C%AF%E5%88%9B%E6%96%B0.pdf), [-附录-](https://file-lianxh.oss-cn-shenzhen.aliyuncs.com/Refs/LianPub/%E6%9D%8E%E5%A2%9E%E7%A6%8F-%E8%BF%9E%E7%8E%89%E5%90%9B-2021-%E9%99%84%E5%BD%95-%E7%BB%9F%E8%AE%A1%E7%A0%94%E7%A9%B6-%E9%9D%9E%E5%9B%BD%E6%9C%89%E8%B5%84%E6%9C%AC%E5%8F%82%E8%82%A1%E4%B8%8E%E5%9B%BD%E4%BC%81%E6%8A%80%E6%9C%AF%E5%88%9B%E6%96%B0.pdf)
-   **连玉君**, 徐想响, 控股股东股权质押与企业短债长用, **金融学季刊**, 2021, 15(4): 26-59. [-PDF-](https://file-lianxh.oss-cn-shenzhen.aliyuncs.com/Refs/LianPub/%E8%BF%9E%E7%8E%89%E5%90%9B-2021-%E9%87%91%E8%9E%8D%E5%AD%A6%E5%AD%A3%E5%88%8A-%E6%8E%A7%E8%82%A1%E8%82%A1%E4%B8%9C%E8%82%A1%E6%9D%83%E8%B4%A8%E6%8A%BC%E4%B8%8E%E4%BC%81%E4%B8%9A%E7%9F%AD%E5%80%BA%E9%95%BF%E7%94%A8.pdf)
-   **连玉君**, 刘畅. 质押新规、股价崩盘风险与公司价值. **中山大学学报**, 2021, 61(5): 182-196. [-PDF-](https://file-lianxh.oss-cn-shenzhen.aliyuncs.com/Refs/LianPub/%E8%BF%9E%E7%8E%89%E5%90%9B-%E5%88%98%E7%95%85-2021-%E4%B8%AD%E5%A4%A7%E5%AD%A6%E6%8A%A5-%E8%B4%A8%E6%8A%BC%E6%96%B0%E8%A7%84-%E8%82%A1%E4%BB%B7%E5%B4%A9%E7%9B%98%E9%A3%8E%E9%99%A9%E4%B8%8E%E5%85%AC%E5%8F%B8%E4%BB%B7%E5%80%BC.pdf)
-   Ye, D., S. Pan, **Y. Lian**, Y.-K. Ng, **2021**, Culture and savings: Why do asians save more?, **The Singapore Economic Review**: 1-31. [-Link-](https://www.worldscientific.com/doi/full/10.1142/S0217590819500607), [-PDF-](https://www.worldscientific.com/doi/epdf/10.1142/S0217590819500607), [-PDF2-](https://file-lianxh.oss-cn-shenzhen.aliyuncs.com/Refs/LianPub/Ye_Lian_2020_Culture-and-Savings_SER.pdf)
-   连玉君, 彭镇, 蔡菁, 杨海生. 经济周期下资本结构同群效应研究. **会计研究**, 2020, (11): 85-97. [-Link-](https://t.cnki.net/kcms/detail?v=X6oIUGaNdGlrcQ3EAxDkIyS7JVN9RZzbI2ci-F4lxs7vX3pbiFS8-nABvY59ioPj8mODCOh1h6K1-YkcqEFjJzUvtkx7-tFLhvO_fIES1l6PUe_LmCyqqq9NAODEXtQZ&uniplatform=NZKPT), [-PDF-](https://file-lianxh.oss-cn-shenzhen.aliyuncs.com/Refs/LianPub/%E8%BF%9E%E7%8E%89%E5%90%9B-%E5%BD%AD%E9%95%87-%E8%94%A1%E8%8F%81-%E6%9D%A8%E6%B5%B7%E7%94%9F-2020-11-%E4%BC%9A%E8%AE%A1%E7%A0%94%E7%A9%B6.pdf)
-   彭镇, 连玉君(\*), 戴亦一 “企业创新激励：来自同群效应的解释”，**科研管理**，2020, 4: 45-53. [-PDF-](https://file-lianxh.oss-cn-shenzhen.aliyuncs.com/Refs/LianPub/%E5%BD%AD%E9%95%87-%E8%BF%9E%E7%8E%89%E5%90%9B-2019-%E7%A7%91%E7%A0%94%E7%AE%A1%E7%90%86-%E4%BC%81%E4%B8%9A%E5%88%9B%E6%96%B0%E6%BF%80%E5%8A%B1_%E6%9D%A5%E8%87%AA%E5%90%8C%E7%BE%A4%E6%95%88%E5%BA%94%E7%9A%84%E8%A7%A3%E9%87%8A.pdf)
-   Peng Zhen, Lian Yujun, Forson Joseph Ato, Peer Effects in R&D Investment Policy: Evidence from China, **International Journal of Finance & Economics**, 2021, 26: 4516-4533. (SSCI), [-Link-](https://onlinelibrary.wiley.com/doi/full/10.1002/ijfe.2028), [-PDF-](https://onlinelibrary.wiley.com/doi/epdf/10.1002/ijfe.2028), [-PDF2-](https://file-lianxh.oss-cn-shenzhen.aliyuncs.com/Refs/LianPub/Peng_Lian_2020_Peer-effects-in-%20RD-investment-policy.pdf).
-   杨海生, 柳建华, 连玉君, 江颖臻, “企业投资决策中的同行效应研究：模仿与学习”， **经济学(季刊)**, 2020, 19 (4): 1375-1400. [-Link-](https://kns.cnki.net/kcms/detail/detail.aspx?dbcode=CJFD&dbname=CJFDLAST2020&filename=JJXU202004012&v=vnwv0yeOYjJw%25mmd2BlUxc6MxanVFhxwRp%25mmd2F6IpffyTQo6%25mmd2Bsuy7Loyopjgp%25mmd2BjNBhek9pFx), [-PDF-](https://file-lianxh.oss-cn-shenzhen.aliyuncs.com/Refs/LianPub/%E6%9D%A8%E6%B5%B7%E7%94%9F-%E6%9F%B3%E5%BB%BA%E5%8D%8E-%E8%BF%9E%E7%8E%89%E5%90%9B-2019-%E7%BB%8F%E6%B5%8E%E5%AD%A6%E5%AD%A3%E5%88%8A-%E4%BC%81%E4%B8%9A%E6%8A%95%E8%B5%84%E5%86%B3%E7%AD%96%E4%B8%AD%E7%9A%84%E5%90%8C%E8%A1%8C%E6%95%88%E5%BA%94%E7%A0%94%E7%A9%B6.pdf)
-   Yang, Liu, Yuanqing Wang, Yujun Lian, and Sunsheng Han. 2020. "Factors and Scenario Analysis of Transport Carbon Dioxide Emissions in Rapidly-Developing Cities." Transportation Research Part D-Transport and Environment 80: 102252. [-Link-](https://doi.org/10.1016/j.trd.2020.102252), [-PDF-](https://file-lianxh.oss-cn-shenzhen.aliyuncs.com/Refs/LianPub/Yang_Lian_2020_Q2-Transportation_Research_Part_D.pdf)
-   陈晓玲, 吴贾, 连玉君. 资本—劳动替代弹性、有偏技术进步与中国工业企业要素相对收入份额\[J\]. **经济科学**, 2019 (4): 81-91. [-Link-](https://kns.cnki.net/kcms/detail/detail.aspx?dbcode=CJFD&dbname=CJFDLAST2019&filename=JJKX201904008&v=MiYkH8v4IDNOpUHlm2A4WC2Byy%25mmd2FEbCk%25mmd2FtrFE5C9bi1ao4XQNgbDmqna4Q6Iz0Vkp), [-PDF-](https://file-lianxh.oss-cn-shenzhen.aliyuncs.com/Refs/LianPub/%E9%99%88%E6%99%93%E7%8E%B2_%E5%90%B4%E8%B4%BE_%E8%BF%9E%E7%8E%89%E5%90%9B_2019_%E8%B5%84%E6%9C%AC_%E5%8A%B3%E5%8A%A8%E6%9B%BF%E4%BB%A3%E5%BC%B9%E6%80%A7_%E6%9C%89%E5%81%8F%E6%8A%80%E6%9C%AF%E8%BF%9B%E6%AD%A5%E4%B8%8E%E4%B8%AD%E5%9B%BD%E5%B7%A5%E4%B8%9A%E4%BC%81%E4%B8%9A%E8%A6%81%E7%B4%A0%E7%9B%B8%E5%AF%B9%E6%94%B6%E5%85%A5%E4%BB%BD%E9%A2%9D.pdf)
-   **连玉君**, 2018, 随机边界模型:进展及stata应用, **郑州航空工业管理学院学报**, (1): 97-112. [-PDF-](https://file-lianxh.oss-cn-shenzhen.aliyuncs.com/Refs/LianPub/%E8%BF%9E%E7%8E%89%E5%90%9B-2018-%E9%9A%8F%E6%9C%BA%E8%BE%B9%E7%95%8C%E6%A8%A1%E5%9E%8B_%E8%BF%9B%E5%B1%95%E5%8F%8AStata%E5%BA%94%E7%94%A8.pdf)
-   **连玉君**, 廖俊平. “如何检验分组回归后的组间系数差异？”，**郑州航空工业管理学院学报**, 2017(6): 97-109. [-Link-](https://t.cnki.net/kcms/detail?v=3uoqIhG8C44YLTlOAiTRKgchrJ08w1e7KuxSPDoq7DTCXFyWbxw4dosRY_cytYzVnMc59G-pPbdxJriX8YSFT8J3rOGAdQkT&uniplatform=NZKPT), [-被引-](https://ref.cnki.net/REF/Detail/GetRefFileDetail?fileName=ZZHK201706010&title=%e5%a6%82%e4%bd%95%e6%a3%80%e9%aa%8c%e5%88%86%e7%bb%84%e5%9b%9e%e5%bd%92%e5%90%8e%e7%9a%84%e7%bb%84%e9%97%b4%e7%b3%bb%e6%95%b0%e5%b7%ae%e5%bc%82%3f&fileCount=265&otherRefCount=264&yearCnt=0&begin=&end=&isOtherCited=False&isInCludedString=Y&sourceRange=), [推文](https://www.lianxh.cn/news/051e3a01cdb19.html), [-PDF-](https://file-lianxh.oss-cn-shenzhen.aliyuncs.com/Refs/LianPub/%E8%BF%9E%E7%8E%89%E5%90%9B-2017-%E5%A6%82%E4%BD%95%E6%A3%80%E9%AA%8C%E5%88%86%E7%BB%84%E5%9B%9E%E5%BD%92%E5%90%8E%E7%9A%84%E7%BB%84%E9%97%B4%E7%B3%BB%E6%95%B0%E5%B7%AE%E5%BC%82.pdf)
-   李增福，汤旭东，连玉君(\*), “中国民营企业社会责任背离之谜”，**管理世界**，2016 (9): 136-148. [-Link-](https://t.cnki.net/kcms/detail?v=X6oIUGaNdGlrAgAg5enwdNuHSVvILWgMK-Q3J0S4qLJKbGDEE3uvbhTG_E0ETd1ZaXGc_1a5O8EwnjnGG-mD-sq81UpA_-kbHG7p0lyW_Jn-fDF9Pu9YNUurzmZXGRbF&uniplatform=NZKPT), [-PDF-](https://file-lianxh.oss-cn-shenzhen.aliyuncs.com/Refs/LianPub/%E6%9D%8E%E5%A2%9E%E7%A6%8F-%E8%BF%9E%E7%8E%89%E5%90%9B-2016-%E7%AE%A1%E7%90%86%E4%B8%96%E7%95%8C-%E4%B8%AD%E5%9B%BD%E6%B0%91%E8%90%A5%E4%BC%81%E4%B8%9A%E7%A4%BE%E4%BC%9A%E8%B4%A3%E4%BB%BB%E8%83%8C%E7%A6%BB%E4%B9%8B%E8%B0%9C.pdf)
-   Huang, B.H., Lian, Yujun(\*), Li, W.S., “How far is Chinese left-behind parents’ health left behind?”, **China Economic Review**, 2016 (37): 15-26. [-Link-](https://doi.org/10.1016/j.chieco.2015.07.002), [-PDF-](https://file-lianxh.oss-cn-shenzhen.aliyuncs.com/Refs/LianPub/Lian_2016_CER_How-far.pdf).
-   彭方平, 周先波, 连玉君(\*), 展凯, “垄断与通货膨胀：理论与证据”，**金融研究**, 2016 (5): 19-34. [-Link-](https://kns.cnki.net/kcms/detail/detail.aspx?dbcode=CJFD&dbname=CJFDLAST2016&filename=JRYJ201605002&v=iEg1HMhdLqDNCkAkwFoqX3%25mmd2B5xRcmjqzN%25mmd2Bw4THrhle9op9uCMjygKPp1i4PBFxgjg), [-PDF-](https://file-lianxh.oss-cn-shenzhen.aliyuncs.com/Refs/LianPub/%E5%BD%AD%E6%96%B9%E5%B9%B3_%E8%BF%9E%E7%8E%89%E5%90%9B_2016_%E9%87%91%E8%9E%8D%E7%A0%94%E7%A9%B6_%E5%9E%84%E6%96%AD%E4%B8%8E%E9%80%9A%E8%B4%A7%E8%86%A8%E8%83%80_%E7%90%86%E8%AE%BA%E4%B8%8E%E8%AF%81%E6%8D%AE.pdf)
-   陈晓玲, 徐舒, 连玉君. “要素替代弹性、有偏技术进步对我国工业能源强度的影响”，**数量经济与技术经济研究**, 2015 (3): 58-76. [-Link-](https://kns.cnki.net/kcms/detail/detail.aspx?dbcode=CJFD&dbname=CJFDLAST2015&filename=SLJY201503004&v=UlKXpnjvy2X7XT8ynt1lDV%25mmd2B%25mmd2BPt%25mmd2BvmYZp0w5XlkmI1JiZaMVBJ7dAMGAHDB4kxoKM)
-   阳义南, 连玉君. “中国社会代际流动性的动态解析——CGSS 与 CLDS 混合横截面数据的经验证据”，**管理世界**, 2015 (4): 79-91. [-Link-](https://t.cnki.net/kcms/detail?v=X6oIUGaNdGn7nPTxVXs9mp-ywXr8yEPvJlvCEjetvl7ywMlC7DVZ_4x3tQ-IeV1Hy7apu_7C3bDubaFAG4gBKhNxO3TPv-_IvLpVmA_l3vWbXSvLr82l8BC0XIQVQ-96&uniplatform=NZKPT), [-PDF-](https://file-lianxh.oss-cn-shenzhen.aliyuncs.com/Refs/LianPub/%E9%98%B3%E4%B9%89%E5%8D%97_%E8%BF%9E%E7%8E%89%E5%90%9B_2015_%E7%AE%A1%E7%90%86%E4%B8%96%E7%95%8C-%E4%B8%AD%E5%9B%BD%E7%A4%BE%E4%BC%9A%E4%BB%A3%E9%99%85%E6%B5%81%E5%8A%A8%E6%80%A7%E7%9A%84%E5%8A%A8%E6%80%81%E8%A7%A3%E6%9E%90.pdf)
-   Ye Dezhu, NG Yew-Kwang, Lian Yujun (\*), “Culture and Happiness”, **Social Indicators Research**, 2015, 123 (2): 519-547. [-Link-](https://link.springer.com/article/10.1007/s11205-014-0747-y), [-PDF-](https://link.springer.com/content/pdf/10.1007/s11205-014-0747-y.pdf), [-PDF2-](https://file-lianxh.oss-cn-shenzhen.aliyuncs.com/Refs/LianPub/Ye-2015-Culture-and-Happiness.pdf)
-   连玉君, 黎文素, 黄必红. “子女外出务工对父母健康和生活满意度影响研究”, **经济学(季刊)**, 2014, 14 (1):185-202. [-Link-](https://t.cnki.net/kcms/detail?v=X6oIUGaNdGlKGCGXJYVC6cmuhtJ8ZW9um1HJgWAv3F--M8xqGfw6M-BcrV4wpqVkeZmMXWXaBKooA75NZJXjVW7wT18cgJuSFmMTG_N9MmQ3z-KiP66jGQ3i-8cfeVEj&uniplatform=NZKPT), [-PDF-](https://file-lianxh.oss-cn-shenzhen.aliyuncs.com/Refs/LianPub/%E8%BF%9E%E7%8E%89%E5%90%9B_2014_%E7%BB%8F%E6%B5%8E%E5%AD%A6%E5%AD%A3%E5%88%8A_%E5%AD%90%E5%A5%B3%E5%A4%96%E5%87%BA%E5%8A%A1%E5%B7%A5%E5%AF%B9%E7%88%B6%E6%AF%8D%E5%81%A5%E5%BA%B7%E5%92%8C%E7%94%9F%E6%B4%BB%E6%BB%A1%E6%84%8F%E5%BA%A6%E5%BD%B1%E5%93%8D%E7%A0%94%E7%A9%B6.pdf)
-   连玉君, 王闻达, 叶汝财. “Hausman 检验统计量有效性的 Monte Carlo 模拟分析”. **数理统计与管理**, 2014, 33 (5): 830-841. [-Link-](https://kns.cnki.net/kcms/detail/detail.aspx?dbcode=CJFD&dbname=CJFD2014&filename=SLTJ201405009&v=aPuqF3qPXJ%25mmd2Bs10sKH%25mmd2FYTR2Xhk5LgV%25mmd2BpqnjdOn%25mmd2BqYN5WdLdZZ94qyHQz3bfYqPvqi)
-   李增福, 黎慧玲, 连玉君, “公允价值变动列报的市场反应”. **会计研究**, 2013 (10): 15-21. [-Link-](https://kns.cnki.net/kcms/detail/detail.aspx?dbcode=CJFD&dbname=CJFDHIS2&filename=KJYJ201310002&v=DLTQkGOxEfcb7NLxzjEVeuaNnP6M18J%25mmd2BH6Ny3WcMdU60ZGxGCM8x5B%25mmd2BU%25mmd2FnHCjQbt)
-   范红忠, 黄永明, 连玉君. “就业生命时间、劳动者收入的持久性与我国居民消费率”. **经济学(季刊)**, 2013, 12 (4): 1209-1230. [-Link-](https://kns.cnki.net/kcms/detail/detail.aspx?dbcode=CJFD&dbname=CJFD2013&filename=JJXU201304005&v=XaVPafMBgP8uShjWCK9kjeJ4e62kttKCDXRMosgVNkggJpXEWNKQQ%25mmd2FyIsPjE%25mmd2Fh%25mmd2Fr)
-   彭方平, 连玉君, 赵慧敏. “经济增长与我国通货膨胀容忍度”.**金融研究**, 2013 (3): 87-100. [-Link-](https://kns.cnki.net/kcms/detail/detail.aspx?dbcode=CJFD&dbname=CJFD2013&filename=JRYJ201303009&v=gazb%25mmd2FTmM57T8yXxjRRwmF5O5CtU1RyWSznFXyIq%25mmd2F7%25mmd2FkQDQ%25mmd2F8HYS9vYlZr3ix4Fod)
-   彭方平, 连玉君, 胡新明, 赵慧敏. “规模经济、卡甘效应与微观货币需求——兼论我国高货币化之谜”. **经济研究**, 2013 (4): 83-93. [-Link-](https://kns.cnki.net/kcms/detail/detail.aspx?dbcode=CJFD&dbname=CJFDLAST2015&filename=JJYJ201304009&v=P6%25mmd2FnkCL%25mmd2Fh8kekqn7Qh1Zz6YAulh1z7J6lNxN0HGlEfuLqw4DGvLLbJhdolVNDc0O)
-   彭方平, 樊海潮，连玉君, 展凯. 我国通货膨胀类型的甄别——基于企业层面的经验证据”. **经济研究**, 2012 (8): 70-80.
-   李增福, 顾研, 连玉君. 税率变动、破产成本与资本结构非对称调整. **金融研究**, 2012 (5): 136-150.
-   陈晓玲, 连玉君. 资本-劳动替代弹性与地区经济增长——德拉格兰德维尔假说的检验. **经济学(季刊)**, 2012, 12 (1): 93-118. [-Link-](https://t.cnki.net/kcms/detail?v=X6oIUGaNdGk7KmamKSdCf4ReyisI-D4NswU7ThX_BCxC1vyDF6Rfp4CEvc-7SagI50y9gXEO8PZwadcDjftJQEiKJ8z8hT0yyvlPxxYMNM-RT8vPg42zNA==&uniplatform=NZKPT)
-   叶德珠, 连玉君, 黄有光, 李东辉. 消费文化、认知偏差与消费行为偏差. **经济研究**, 2012 (2): 80-92. [-Link-](https://t.cnki.net/kcms/detail?v=X6oIUGaNdGkvA89Jx3ExaGG62qx5f0VjrV4bURTBxcfGnD5f_AKgRFD4m76yYQzXhMwSNB-jAdTn_TKb7CQo86knJ2b_ShZ2dBr0UerY7v07aCdgUVJMIA==&uniplatform=NZKPT)
-   鲁晓东, 连玉君. 中国工业企业全要素生产率估计：1999-2007. **经济学(季刊)**, 2012, 11 (2): 541-558. [-Link-](https://t.cnki.net/kcms/detail?v=X6oIUGaNdGkTG5M2fn0qzvVNE_rl1enAK1WfNOt_Sfw3KSFUbG_KfclEVyMBr0SaV1DDa0fTvJFjQP50PKzhuAjkwvasa-xLn0MP25oATZTfyi3weAJ40Q==&uniplatform=NZKPT)
-   连玉君, 刘醒云, 苏治. 现金持有的行业特征：差异性与收敛性, **会计研究**, 2011 (7): 66-72. [-Link-](https://kns.cnki.net/kcms/detail/detail.aspx?dbcode=CJFD&dbname=CJFD2011&filename=KJYJ201107011&v=Mxv4akbuWn4GLh2h3dDTmwIRNSZMCgi73JUoOjZCpCsBbSl%25mmd2FtWYHQr5LIWc%25mmd2BcfSd)
-   苏治, 连玉君. 中国上市公司代理成本的估算——基于异质性随机前沿模型的经验分析，**管理世界**，2011 (6): 174-175+188. [-Link-](https://kns.cnki.net/kcms/detail/detail.aspx?dbcode=CJFD&dbname=CJFD2011&filename=GLSJ201106021&v=%25mmd2F5UaKggUD8M3sxkjrf0Nic0xDAhAF7uxI2IoMvEK0tge%25mmd2F6p9TnEb2XphRy7ASZbO)
-   Lian, Y.J., Z. Su, Y.D. Gu, Evaluating the Effects of Equity Incentives using PSM: Evidence from China. Frontiers of Business Research in China, 2011, 5 (2): 266-290. [-Link-](https://academic.microsoft.com/paper/2065970386)
-   卢洪友, 连玉君, 卢盛峰. 中国医疗服务市场中的信息不对称程度测算. **经济研究**, 2011 (04): 94-106. [-Link-](https://t.cnki.net/kcms/detail?v=X6oIUGaNdGnsJmC_8cJnc03I9gC9gi9WbKE7uoRnIajq5DNmg6d-9kr0GiuOhz9emyRPnkX98-d8kFybsssJUjiINBPLgV25sfGET7ON0efc6SXsjEvSag==&uniplatform=NZKPT)
-   李增福, 董志强, 连玉君. 应计项目盈余管理还是真实活动盈余管理？——基于我国 2007 年所得税改革的研究, **管理世界**, 2011 (1): 121-134. [-Link-](https://t.cnki.net/kcms/detail?v=3uoqIhG8C44YLTlOAiTRKgchrJ08w1e7tvjWANqNvp80Xwf4tbZjOz0PdH-rNBDC2Y01k7wwBVX3SvmIqTzYWrKlW6poH7Hd&uniplatform=NZKPT&uid=WEEvREcwSlJHSldSdmVqM1BLVW9SQVdSTVZqQlNQcDZrRXVwdnI1emF1az0=$9A4hF_YAuvQ5obgVAqNKPCYcEjKensW4IQMovwHtwkF4VYPoHbKxJw!!)
-   彭方平, 连玉君. 2010, 我国货币政策的成本效应, **管理世界**, 12, 27-33. [-Link-](https://kns.cnki.net/kcms/detail/detail.aspx?dbcode=CJFD&dbname=CJFD2010&filename=GLSJ201012005&v=J6QKr7SMRzk6hv6UUkcCc275f4FnZSo5vYnLnTyf6ihjoshiuagz1yvXTF6oiFfx)
-   连玉君, 苏治, 彭方平. 融资约束与流动性管理行为. **金融研究**, 2010 (10): 158-171. [-Link-](https://t.cnki.net/kcms/detail?v=X6oIUGaNdGlP4M0tsXPiU6wmWoPKCiNWl1JbNNWwXQBIcVBwCPyliLgTRfbuMIqK1EeqoxlUM72AX1vpn0OdGErQbDV9xvFMg6_gYJsSM_cbo61A1RPUZQ==&uniplatform=NZKPT)
-   彭方平, 连玉君. 我国行业周期非同步效应——基于微观视角, **经济学(季刊)**, 2010, 9 (3): 1071-1082.\
-   连玉君, 苏治. 融资约束、不确定性与上市公司投资效率. **管理评论**, 2009 (01)：19-27. [-Link-](https://t.cnki.net/kcms/detail?v=X6oIUGaNdGmGV8tRJ4vGxdlHxknuoD_aDUi3zjKlMLZu-pVFXVfGUgSD0p-RZmf-Ae1Sb5ExvuIh0_BadtH5y8C_oGQYz4Y3iZDpx8Fh760TBTneXv7VrA==&uniplatform=NZKPT)
-   连玉君, 苏治, 丁志国. 现金-现金流敏感性能检验融资约束假说吗? **统计研究**, 2008 (10): 92-99. [-Link-](https://kns.cnki.net/kcms/detail/detail.aspx?dbcode=CJFD&dbname=CJFD2008&filename=TJYJ200810016&v=IdIBnwKGB4SD0iPVpnEzucO82oLDRPxt57XCjB5vLshcPO3ax%25mmd2BzwMmv3KIpthKlB)
-   连玉君, 苏治. 上市公司现金持有:静态权衡还是动态权衡？**世界经济**, 2008 (10): 84-96. [-Link-](https://kns.cnki.net/kcms/detail/detail.aspx?dbcode=CJFD&dbname=CJFD2008&filename=SJJJ200810010&v=8myfCWmARKYWlIKzZjg4IVqjoOfF5CQezmjy2%25mmd2BJQmkIgUM710iD5nCELC7uU%25mmd2FtOM)
-   连玉君, 程建. 投资-现金流敏感性：融资约束还是代理成本. **财经研究**, 2007 (2): 37-46. [-Link-](http://www.cnki.com.cn/Article/CJFDTotal-CJYJ200702003.htm)

## 科研项目

1.  广东省自然科学基金委员会，面上项目，2023A1515012307，科创板IP0 定价效率研究，2023.1.1-2025.12.31，资助额：10 万元. 负责人：连玉君
2.  广东省自然科学基金委员会，面上项目，2020A1515011291，股权质押的风险传染与防范措施研究，2019.10.1-2022.9.30，资助额：10 万元. 已结项，主持
3.  国家自然科学基金委员会，面上项目，71672206，中国上市公司财务决策中的同群效应研究，2017.01-2020.12, 资助额：48 万元，结项申请，主持
4.  国家自然科学基金委员会，青年项目，71002056，中国上市公司流动性管理行为研究：动机、方式与经济后果，2011.01-2013.12，资助额：18 万元，已结项(评定为“优”)，主持
5.  国家税务总局委托项目，编号：10000-71210549，“基于随机边界分析的税收流失率估算研究”，2016/09-2017/09, 资助额：20 万, 已结项。
6.  广东省省委宣传部，广东省社科规划项目，LLYJ1313，打造“理论粤军”2013 年度重大现实问题研究招标课题“广东做大做强民营经济研究”，2014.01-2016.01，资助额：25 万元，已结项，主持
7.  广东省自然科学基金委员会，科技计划项目，2011B040400006，促进广东高新技术业和科技服务业协同发展的科技服务模式研究，2011.09-2012.08，资助额：20 万元，已结项，主持
8.  教育部人文社会科学研究基金青年项目“转型背景下中国上市公司投资效率研究”，(编号：09YJC790269)，2009.12-2012.12. 负责人: 连玉君. 资助额：5 万. (已结项)
9.  广东省自然科学基金项目“广东科技型企业研发模式和研发效率研究”，（9451027501002497），2009.10-2011.10. 负责人: 连玉君. 资助额：3 万. (已结项)